### ISSUE TITLE
Does not build with latest OFP/ODP

### ISSUE THREAD

**Issue by krisk0** [OpenFastPath/nginx_ofp#4]
README says 'Get latest OFP'.

Such instruction never works.

Source code must be patched due to changes in OFP API. `ofp_init_global_t` should be replaced by `ofp_global_param_t`. `OFP_PKT_RX_BURST_SIZE` and `OFP_PKTOUT_QUEUE_MAX` should be replaced, too. 

`-lconfig` `-lnuma` `-latomic` should be added to `CORE_LIBS` in `auto/make`. `libodp-dpdk.a` and `libodphelper-linux.a` should be replaced with `libodp-linux.a` and `libodphelper.a`.

**Comment by dongbin1024** [comment]
> OFP_PKT_RX_BURST_SIZE and OFP_PKTOUT_QUEUE_MAX should be replaced, too

hi，I'm tring too, and these two should be replaced with what?

**Comment by MatiasElo** [comment]
> > OFP_PKT_RX_BURST_SIZE and OFP_PKTOUT_QUEUE_MAX should be replaced, too
> 
> hi，I'm tring too, and these two should be replaced with what?

Hi, what is the exact problem you are having? Looking at the latest code it seems that at least most of these issues should be already fixed.

**Comment by dongbin1024** [comment]
1, Get latest OFP;
2, compile nginx-ofp: error: OFP_PKTIN_QUEUE_MAX and OFP_PKT_RX_BURST_SIZE undefined 
how to solve this problem?

**Comment by MatiasElo** [comment]
> 1, Get latest OFP;
> 2, compile nginx-ofp: error: OFP_PKTIN_QUEUE_MAX and OFP_PKT_RX_BURST_SIZE undefined
> how to solve this problem?

Okay, I was looking at the wrong project.

I'll check how big task it would be to update the nginx integration but for now you can try to replace the defines with nginx specific ones. 
E.g.
`#define MAX_INPUT_QUEUES 32`
OFP_PKTIN_QUEUE_MAX -> MAX_INPUT_QUEUES

`#define PKT_BURST_SIZE 16`
OFP_PKT_RX_BURST_SIZE -> PKT_BURST_SIZE

Also, `ofp_init_global_t ` has been renamed to `ofp_global_param_t`.

**Comment by matiaselo** [comment]
At least the build is passing with these modifications: https://github.com/matiaselo/nginx_ofp/commits/dev/update

**Comment by MatiasElo** [comment]
PR #6 should fix these issues.

**Comment by dongbin1024** [comment]
omg, i also find the ofp_init_global_param has not been used,so arp timer always failed.you finally solve this problem , thank you very much

**Comment by MatiasElo** [comment]
> omg, i also find the ofp_init_global_param has not been used,so arp timer always failed.you finally solve this problem , thank you very much

You're welcome. The fixes have now been merged to master.
